apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ambient-gateway
  namespace: default
spec:
  # Istio가 이 게이트웨이를 관리하도록 지정
  gatewayClassName: istio
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same