name: "Terraform Apply"
on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: "Terraform Deploy"
    runs-on: ubuntu-latest
    
    # WIF 인증을 위해 깃허브 토큰 권한을 허용해야 합니다 (필수!)
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP (WIF)
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.TF_SA_EMAIL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve